config/routes.rb
Tt::Application.routes.draw do
  get "user/show"

  get "pages/home"

  get "pages/about"

  get "videos/index"

  devise_for :users
  resources :videos

  root :to => "videos#index"

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable,
  # :confirmable and :activatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation,
                  :name, :username, :avatar

  # :dependent => :destroy ensures that all a user's videos are destroyed when
  # the user is destroyed.
  has_many :videos, :dependent => :destroy

  # get profile pic using paperclip
  # store two versions: thumbnail (32x32) and medium (300x300)
  has_attached_file :avatar,
                    :default_url => "default_avatar.jpg",
                    :styles => {
                      :thumb => "32x32#",
                      :medium => "300x300>"
                    },
                    :dependent => :destroy
  # validates_attachment_presence :avatar
  validates_attachment_size :avatar, :less_than => 5.megabytes
  validates_attachment_content_type :avatar,
                                    :content_type => ['image/jpeg', 'image/png',
                                                      'image/gif']
  # paperclip extended validations
  validates_attachment_extension :avatar,
                                 :extensions => %w[jpg jpeg gif png]

  def video_feed
    Video.where("user_id = ?", id)
  end

end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user
  attr_accessible :name, :description, :clip

  # order reverse-chronologically, by default
  default_scope :order => 'videos.created_at DESC'

  validates :description, :presence => true, :length => { :maximum => 140 }
  validates :user_id, :presence => true

  # make Paperclip happy
  # TODO: add content-type and filename extension check
  has_attached_file :clip
  validates_attachment_presence :clip

  # FSM: might come in handy at some point
  acts_as_state_machine :initial => :pending
  state :pending
  state :uploading
  state :converting
  state :converted, :enter => :set_new_filename
  state :error

  event :upload do
    transitions :from => :init, :to => :uploading
  end

  event :convert do
    transitions :from => :pending, :to => :converting
  end

  event :converted do
    transitions :from => :converting, :to => :converted
  end

  event :failed do
    transitions :from => :converting, :to => :error
  end

  def convert
    self.convert!
    cmd = convert_command
    puts "[CONVERT_COMMAND] #{cmd}"
    success = system(cmd)
    if success && $?.exitstatus == 0
      self.converted!
    else
      self.failed!
    end
  end

  private

  def get_max_duration
    15 #seconds
  end

  def convert_command
    flv = File.join(File.dirname(clip.path), "#{id}.flv")
    max_t = get_max_duration
    File.open(flv, 'w')

    command = <<-end_command
      ffmpeg -i #{ clip.path }  -ar 22050 -ab 32 -acodec libmp3lame
      -s 480x360 -vcodec flv -r 25 -t #{max_t} -qscale 8 -f flv -y #{ flv }
    end_command
    command.gsub!(/\s+/, " ")
  end

  def set_new_filename
    update_attribute(:clip_file_name, "#{id}.flv")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_filter :authenticate_user!

  def index
    @user = current_user
    @videos ||= current_user.video_feed
  end

  def show
    @user = current_user
    @video ||= current_user.video_feed.find(params[:id])
  end

  def new
    @video = Video.new
  end

#  def create
#    @video = Video.new(params[:video])
#    if @video.save
#      @video.convert
#      redirect_to @video, :notice => "Successfully created video."
#    else
#      render :action => 'new'
#    end
#  end

  def create
    @video = current_user.videos.build(params[:video])
    if @video.save
      @video.convert
      redirect_to @video, :notice => "Successfully uploaded video."
    else
      render :action => 'new'
    end
  end

  def edit
    @video = current_user.videos.find(params[:id])
  end

  def update
    @video = current_user.videos.find(params[:id])
    if @video.update_attributes(params[:video])
      redirect_to @video, :notice  => "Successfully updated video."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @video = current_user.videos.find(params[:id])
    @video.destroy
    redirect_to videos_url, :notice => "Successfully destroyed video."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>

  <body>
    <div id="header">
      <div id="user_nav">
        <% if user_signed_in? %>
          [<%= link_to "#{current_user.name}", user_show_path %>]
          [<%= link_to "videos", videos_index_path %>]
          [<%= link_to "logout", destroy_user_session_path %>]
        <% else %>
          [<%= link_to "register", new_user_registration_path %>]
          [<%= link_to "videos", videos_index_path %>]
          [<%= link_to "login", new_user_session_path %>]
        <% end %>
      </div>
    </div>

    <div class="clear"></div>

    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>

</html>

app/views/videos/_form.html.erb
<%= form_for @video , :html => { :multipart => true } do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :clip %><br />
    <%= f.file_field :clip %>
  </p>
   <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/videos/edit.html.erb
<% title "Edit Video" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @video %> |
  <%= link_to "View All", videos_path %>
</p>

app/views/videos/index.html.erb
<% title "Videos" %>
<h1>
  <%= image_tag @user.avatar.url(:thumb) %>
  <%= @user.name %>
</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
  </tr>
  <% for video in @videos %>
    <tr>
      <td><%= video.name %></td>
      <td><%= video.description %></td>
      <td><%= link_to "Show", video %></td>
      <td><%= link_to "Edit", edit_video_path(video) %></td>
      <td><%= link_to "Destroy", video, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Video", new_video_path %></p>

app/views/videos/new.html.erb
<% title "New Video" %>

<%= render 'form' %>

<p><%= link_to "Back to List", videos_path %></p>

app/views/videos/show.html.erb
<% title "Video" %>
<h3>
  <%= image_tag @user.avatar.url(:thumb) %>
  <%= current_user.name %>
</h3>

<p>
  <strong>Name:</strong>
  <%= @video.name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>
<p>
    Trying to show: <%= @video.clip.url %>

    <%= javascript_include_tag 'swfobject' %>
    <div id="player">
    You need to have <%= link_to 'Flash Player', 'http://www.adobe.com/shockwave/download/download.cgi?P1_Prod_Version=ShockwaveFlash' %> installed to display this video
  </div>

  <script type="text/javascript">
    var so = new SWFObject('/flash/player.swf', 'mpl', '480', '360', '8');
    so.addParam('allowscriptaccess', 'always');
    so.addParam('allowfullscreen', 'true');
    so.addVariable('height', '360');
    so.addVariable('width', '480');
    so.addVariable('file', '<%= @video.clip.url %>');
    so.write('player');
  </script>

</p>
<p>
  <%= link_to "Edit", edit_video_path(@video) %> |
  <%= link_to "Destroy", @video, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", videos_path %>
</p>